# Generated by Django 6.0.6 on 2026-09-04 04:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Egyptian Residential Tariff', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_fee_mode', models.CharField(choices=[('current_slice', 'Current slice only - one fee, from the slice reached'), ('cumulative', "Cumulative - sum of every slice's fee up to and including the current one")], default='current_slice', help_text="How the customer service fee is totaled. Postpaid monthly bills typically show a single fee for the slice reached. Prepaid ('abu كارت') meters deduct a fee at EVERY slice crossing in real time, so those fees accumulate as consumption climbs.", max_length=20)),
                ('unread_meter_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat fee charged when the meter could not be read this cycle.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage of energy charge'), ('per_kwh', 'Per kWh')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.tariff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('consumption_kwh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('energy_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_service_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transition_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unread_meter_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.tariff')),
            ],
            options={
                'ordering': ['-billing_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-based position of this slice in the ladder.')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('min_kwh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for the open-ended last slice.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate_piastres', models.DecimalField(decimal_places=2, help_text='Price per kWh, in piastres (100 pt = 1 EGP).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('customer_service_fee', models.DecimalField(decimal_places=2, help_text='EGP service fee that applies once this slice is reached.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('billing_mode', models.CharField(choices=[('marginal', "Progressive - only this slice's own kWh at its own rate"), ('flat_full', "Flat - entire consumption billed at this slice's rate once reached")], default='marginal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='core.tariff')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('deduction_amount', models.DecimalField(decimal_places=2, help_text='EGP deducted the moment consumption enters this slice.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_rules', to='core.tariff')),
                ('triggering_slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_rules', to='core.tariffslice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='tariffslice',
            constraint=models.UniqueConstraint(fields=('tariff', 'order'), name='unique_slice_order_per_tariff'),
        ),
    ]
